# Exported from Render on 2026-05-20T19:27:53Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      previews:
        generation: automatic
      name: workflow-keyword-detector
      runtime: python
      repo: https://github.com/Mattrender/workflow-keyword-detector
      plan: starter
      envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Workflowsdb
          property: connectionString
      region: oregon
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn app:app
      autoDeployTrigger: commit
      rootDir: dashboard
    databases:
    - name: Workflowsdb
      databaseName: workflowsdb
      user: workflowsdb_user
      plan: basic-256mb
      region: oregon
      ipAllowList:
      - source: 172.56.195.239/32
        description: Matt Bemis (matt.bemis@render.com)
      postgresMajorVersion: "18"
      diskSizeGB: 1
